//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int Id { get; set; }
        public Nullable<double> distance_total_min { get; set; }
        public Nullable<double> distance_total { get; set; }
        public Nullable<double> distance_vao_min { get; set; }
        public Nullable<double> distance_vao_max { get; set; }
        public Nullable<double> distance_base_reinforcement_max { get; set; }
    }
}
